// This file is autogenerated, any manual changes will be lost after regeneration
import * as dto from './dto';
import * as enums from './enums';
import axios from 'axios';


export namespace SampleController {
    export async function getRegisteredUsers(userType: enums.UserType): Promise<dto.UserDto[]> {
        const response = await axios.request({
            url: '/Sample/GetRegisteredUsers',
            method: 'GET',
            params: { userType },
            data: null
        });

        return response.data
    }

    export async function getRegisteredUsersWithNullableParam(userType: enums.UserType | undefined | null): Promise<dto.UserDto[]> {
        const response = await axios.request({
            url: '/Sample/GetRegisteredUsersWithNullableParam',
            method: 'GET',
            params: { userType },
            data: null
        });

        return response.data
    }

    export async function getMaybeNullReturn(number: number | undefined | null): Promise<dto.DtoInModelsFolder | undefined | null> {
        const response = await axios.request({
            url: '/Sample/GetMaybeNullReturn',
            method: 'GET',
            params: { number },
            data: null
        });

        return response.data
    }
}
