// This file is autogenerated, any manual changes will be lost after regeneration
import * as enums from './enums';
import * as dto from './dto';

import axios from 'axios';

export namespace SampleController {
    export async function getRegisteredUsers(userType: enums.UserType): Promise<dto.UserDto[]> {
        const response = await axios.request({
            url: '/Sample/GetRegisteredUsers',
            method: 'GET',
            params: { userType },
            data: null
        });

        return response.data
    }
    export async function getMaybeNullReturn(number: number | null): Promise<dto.DtoInModelsFolder | null> {
        const response = await axios.request({
            url: '/Sample/GetMaybeNullReturn',
            method: 'GET',
            params: { number },
            data: null
        });

        return response.data
    }
}
