// This file is autogenerated, any manual changes will be lost after regeneration


export interface DtoInModelsFolder {
    value: string | undefined | null;
}

export interface UserDto {
    valueNullableByMaybeNull: DtoInModelsFolder | undefined | null;
    firstName: string | undefined | null;
    lastNameNotNull: string;
}
