// This file is autogenerated, any manual changes will be lost after regeneration
import * as enums from './enums';


export interface UserDto {
    firstName: string | null;
    lastName: string | null;
}
