// This file is autogenerated, any manual changes will be lost after regeneration
import * as enums from './enums';


export interface DtoInModelsFolder {
    value: string | null;
}

export interface UserDto {
    valueNullableByMaybeNull: DtoInModelsFolder | null;
    firstName: string | null;
}
