// This file is autogenerated, any manual changes will be lost after regeneration


export enum EnumType {
    FirstValue = 0,
    SecondValue = 1,
}

export namespace EnumType {
    export function getDescription(enumValue: EnumType) {
        switch (enumValue) {
            case EnumType.FirstValue: return 'First value';
            case EnumType.SecondValue: return 'Second value';
        }
    }

    export function getShortName(enumValue: EnumType) {
        switch (enumValue) {
            case EnumType.FirstValue: return 'First value';
            case EnumType.SecondValue: return 'Second value';
        }
    }

    export function allEnums() {
        return [EnumType.FirstValue, EnumType.SecondValue];
    }
}
