// This file is autogenerated, any manual changes will be lost after regeneration


export enum UserType {
    Regular = 0,
    Admin = 1,
}

export namespace UserType {
    export function getDescription(enumValue: UserType) {
        switch (enumValue) {
            case UserType.Regular: return 'Regular';
            case UserType.Admin: return 'Admin';
        }
    }

    export function getShortName(enumValue: UserType) {
        switch (enumValue) {
            case UserType.Regular: return 'Regular';
            case UserType.Admin: return 'Admin';
        }
    }

    export function allEnums() {
        return [UserType.Regular, UserType.Admin];
    }
}
